import { defineRouteMiddleware } from '@astrojs/starlight/route-data';
import type { StarlightRouteData } from '@astrojs/starlight/route-data';

type SidebarEntry = StarlightRouteData['sidebar'][number];
type SidebarLink = Extract<SidebarEntry, { type: 'link' }>;
type SidebarGroup = Extract<SidebarEntry, { type: 'group' }>;

/**
 * Multi-sidebar: each product gets its own tree.
 *
 * `astro.config.mjs` declares one top-level group per product (`tophhie-social`
 * and so on), each wrapping a single autogenerated directory. This middleware keeps
 * only the group belonging to the product segment of the current URL and lifts that
 * group's children to the top level, so `/tophhie-social/*` shows Tophhie Social's
 * subsections and nothing else.
 *
 * It also turns folder names into readable group labels, so a subsection folder can
 * stay kebab-case on disk (`getting-started`) and still read as "Getting started" in
 * the sidebar.
 *
 * Pages outside a product (the root landing page, 404) keep the full list, which
 * renders as a collapsed index of every product.
 */
export const onRequest = defineRouteMiddleware((context) => {
	const route = context.locals.starlightRoute;

	// Starlight caches one sidebar tree per locale and reuses it for every page,
	// so relabelling has to happen on copies. Mutating in place would leak into
	// other routes and depend on build order.
	route.sidebar = withReadableGroupLabels(route.sidebar);

	// The docs loader gives the root index page an empty id; every other page is
	// prefixed with its product folder.
	const product = route.id.split('/')[0];
	if (!product) return;

	const group = route.sidebar.find(
		(entry): entry is SidebarGroup =>
			entry.type === 'group' && autogeneratedDirectory(entry.entries) === product
	);
	if (!group) return;

	route.sidebar = group.entries;

	// `pagination` was computed against the full multi-product tree, which would let
	// prev/next walk off the end of one product and into the next. Recompute it inside
	// the scoped tree, unless the page set prev/next explicitly.
	const frontmatter = route.entry.data;
	if (frontmatter.prev === undefined && frontmatter.next === undefined) {
		const links = flattenLinks(route.sidebar);
		const index = links.findIndex((link) => link.isCurrent);
		if (index !== -1) {
			route.pagination = { prev: links[index - 1], next: links[index + 1] };
		}
	}
});

/**
 * Copy a sidebar tree, rewriting autogenerated group labels from folder names to
 * sentence case. Link entries are passed through by reference so Starlight's
 * `isCurrent` bookkeeping keeps working.
 */
function withReadableGroupLabels(entries: SidebarEntry[]): SidebarEntry[] {
	return entries.map((entry) => {
		if (entry.type !== 'group') return entry;
		const isAutogenerated = 'autogenerate' in entry && Boolean(entry.autogenerate);
		return {
			...entry,
			label: isAutogenerated ? sentenceCase(entry.label) : entry.label,
			entries: withReadableGroupLabels(entry.entries),
		};
	});
}

/** `accounts-and-handles` → `Accounts and handles`. Idempotent. */
function sentenceCase(label: string): string {
	const words = label.replace(/[-_]+/g, ' ').trim();
	return words.charAt(0).toUpperCase() + words.slice(1);
}

/**
 * The directory an autogenerated subtree came from.
 *
 * Starlight stamps every entry it generates for `autogenerate: { directory }` with
 * that directory, meaning the configured one rather than the nested path, so the
 * first stamped descendant identifies which product a wrapper group holds.
 */
function autogeneratedDirectory(entries: SidebarEntry[]): string | undefined {
	for (const entry of entries) {
		if ('autogenerate' in entry && entry.autogenerate) return entry.autogenerate.directory;
		if (entry.type === 'group') {
			const directory = autogeneratedDirectory(entry.entries);
			if (directory) return directory;
		}
	}
	return undefined;
}

function flattenLinks(entries: SidebarEntry[]): SidebarLink[] {
	return entries.flatMap((entry) => (entry.type === 'group' ? flattenLinks(entry.entries) : entry));
}
